### DISCUSSION TITLE
How do I configure OIDC using env variables for automatic deployment?

### DISCUSSION THREAD

**Discussion by MalteMagnussen** [Forceu/Gokapi#163] [Q&A] [answered]
https://gokapi.readthedocs.io/en/latest/advanced.html#available-environment-variables

I can't find how to set the env variables to connect to Entra ID.

**Comment by MalteMagnussen** [comment]
How can this run in Kubernetes? Do I really need to do the UI setup every time a pod starts? 

```

    spec:  
      containers:
      - image: REDACTED/mirror/docker.io/f0rc3/gokapi:v1.8.2
        imagePullPolicy: "IfNotPresent"
        name: gokapi
        
        # https://gokapi.readthedocs.io/en/latest/advanced.html#available-environment-variables
        env:
        # If not using OIDC ENTRA ID
        - name: GOKAPI_USERNAME
          value: "admin"
        - name: GOKAPI_PASSWORD
          valueFrom:
            secretKeyRef:
              name: gokapi-secret
              key: GOKAPI_PASSWORD

        # S3 Bucket info
        - name: GOKAPI_AWS_BUCKET
          value: "REDACTED-gokapi"
        - name: GOKAPI_AWS_REGION
          value: "us-east-1"
        - name: GOKAPI_AWS_KEY
          value: "REDACTED"
        - name: GOKAPI_AWS_KEY_SECRET
          valueFrom:
            secretKeyRef:
              name: gokapi-secret
              key: GOKAPI_AWS_KEY_SECRET
        - name: GOKAPI_AWS_ENDPOINT
          value: "REDACTED"

        # Sets the webserver port
        - name: GOKAPI_PORT
          value: "53842"
        
        # Sets the maximum allowed file size in MB
        - name: GOKAPI_MAX_FILESIZE
          value: "102400"  # 100GB

        # Sets the amount of RAM in MB that can be allocated for an upload.
        # Any upload with a size greater than that will be written to a temporary file
        - name: GOKAPI_MAX_MEMORY_UPLOAD
          value: "20"

        volumeMounts:
        - name: data-volume
          mountPath: /app/data
        - name: config-volume
          mountPath: /app/config
```

How can I configure it to just start, without having to use the UI to configure it? 

The Docs say I can set it up without any interacting, by setting env variables, but I can't seem to make it work: https://gokapi.readthedocs.io/en/latest/advanced.html#environment-variables
