### DISCUSSION TITLE
How to set up fluent-bit sidecar to parse logs

### DISCUSSION THREAD

**Discussion by MalteMagnussen** [Forceu/Gokapi#168] [Show and tell]
How to set up a fluent-bit sidecar for Gokapi, that can parse the Download logs into json fields.

`parsers.conf`

```
# https://docs.fluentbit.io/manual/pipeline/parsers/configuring-parser
[PARSER]
  Name timestamp
  Format regex
  Regex ^(?<timestamp>[A-Za-z]{3}, \d{2} [A-Za-z]{3} \d{4} \d{2}:\d{2}:\d{2} [A-Za-z]{3}) (?<message>.+)$
  Time_Key timestamp
  Time_Format %a, %d %b %Y %H:%M:%S %Z

[PARSER]
  Name download
  Format regex
  Regex ^\s*Download: Filename (?<filename>[^,]*), IP (?<ip>[^,]*), ID (?<id>[^,]*), Useragent (?<useragent>.*)$
```

`fluent-bit.conf`

```
[SERVICE]
    Flush 1
    Log_Level info
    Parsers_File ./parsers.conf
    Daemon off

# https://docs.fluentbit.io/manual/pipeline/inputs/tail
[INPUT]
    Name tail
    Path /opt/bitnami/fluent-bit/log/log.txt
    Tag gokapi.*

[FILTER]
    Name Parser
    Match *
    Parser timestamp
    Key_Name log

[FILTER]
    Name Parser
    Match *
    Parser download
    Key_Name message

# https://docs.fluentbit.io/manual/pipeline/outputs/standard-output
[OUTPUT]
    Name stdout
    Match *
    Format json_lines
```

`deployment.yaml` - Removed all the fluff

```
kind: Deployment
spec:
  template:
    spec:
      containers:
        - image: f0rc3/gokapi:v1.8.4
          name: gokapi

          volumeMounts:
            - name: data-volume
              mountPath: /app/data
            - name: config-volume
              mountPath: /app/config

        - name: fluent-bit
          image: docker.io/bitnami/fluent-bit:3

          volumeMounts:
            - name: data-volume
              mountPath: /opt/bitnami/fluent-bit/log
            - name: fluent-bit-config
              mountPath: /opt/bitnami/fluent-bit/conf/fluent-bit.conf
              subPath: fluent-bit.conf
            - name: fluent-bit-config
              mountPath: /opt/bitnami/fluent-bit/conf/parsers.conf
              subPath: parsers.conf

      volumes:
        - name: data-volume
          emptyDir: {}
        - name: config-volume
          secret:
            secretName: gokapi-config
        - name: fluent-bit-config
          configMap:
            name: fluent-bit-config
```

`kustomization.yaml`

```
kind: Kustomization

resources:
- ./deployment.yaml
- ./service.yaml

configMapGenerator:
  - name: fluent-bit-config
    files:
      - ./fluent-bit/fluent-bit.conf
      - ./fluent-bit/parsers.conf
```
