### DISCUSSION TITLE
Question: Changing style of the app

### DISCUSSION THREAD

**Discussion by MalteMagnussen** [Forceu/Gokapi#184] [Q&A] [answered]
We are trying to update the styling of Gokapi to fit our company style-guide.

For local development, we use a `docker-compose.yml` file:

```yaml
services:
  gokapi:
    build: .
    environment:
      - DOCKER_NONROOT="false"
    ports:
      - "53842:53842"
    develop:
      watch:
        - action: rebuild
          path: ./web/static/
          target: /app/static/
        - action: rebuild
          path: ./web/templates/
          target: /app/templates/
    volumes:
      - ./development/config:/app/config
      - ./development/data:/app/data
    user: "1000:1000"
```

To run this, we do

```
docker compose up
# https://github.com/moby/moby/issues/3206
# first time, we have to do:
sudo chown -R 1000:1000 ./
```

Here is the `Dockerfile`

```
FROM gokapi:v1.8.4

COPY ./web/templates/ /app/templates/
COPY ./web/static/ /app/static/
```

If we make changes to the images, or the html templates, then the change is visible in the app.

But if we make changes to the css `web/static/css/cover.css` then that doesn't work.

The reason it does not work, is probably because the css is "minified" here: https://github.com/Forceu/Gokapi/blob/master/cmd/gokapi/Main.go#L37-L42

How can we best implement the changes to the style of the app?
