### DISCUSSION TITLE
Default File Size Cap

### DISCUSSION THREAD

**Discussion by truthsword** [Forceu/Gokapi#204] [General]
I'm uploading to B2 (S3) and so far I am OK uploading 10 MB files. But when I try a 10 GB file, the file appears to start loading (green bar quickly advances to the rightmost end, but then stays with no actual upload to B2 (confirmed by router traffic. 

![](https://i.imgur.com/vm8ix6V.png)

I have just a basic docker container:

```
services:
  gokapi:
    image: f0rc3/gokapi:latest
    container_name: gokapi
    restart: unless-stopped
    ports:
      - 53842:53842
    volumes:
      - data:/app/data
      - config:/app/config
 ```

Is there a default file size cap for upload? I can manually upload to B2, so this isn't seemingly a B2 constraint.

I noticed an environmental varaible to set a cap, so I'm wondering if there is some built-in cap when no environmental entry is in the docker compose. Thank you!

**Comment by spacefrogfeds** [comment]
For me the config.json file contained a cap and it was set to 102400(MB) so 100gb. I limited mine to 300mb and noticed when dragging a file that exceeds the limit, it will not display any error, just shows 0% progress.

**Reply by Forceu** [reply]
Thanks for the feedback, that is indeed a bug that was most likely introduced at some point in the last versions. I tracked it in #213 and it will be fixed with the next update

**Reply by Forceu** [reply]
Fixed in [520f796](https://github.com/Forceu/Gokapi/commit/520f796c5094a0d3f6ac0bc82d9ce06e95c507dd)

**Comment by truthsword** [comment]
> the config.json file contained a cap and it was set to 102400(MB) so 100gb

So here is the rub... 1024000(KB, not MB) is 100GB. 
![](https://i.imgur.com/jCpkMaO.png)
That may explain why my 500MB file failed. This may also affect the environmental variable "GOKAPI_MAX_FILESIZE"
![](https://i.imgur.com/bJNkRJy.png)
Check my math, I could have slipped a decimal...

**Reply by truthsword** [reply]
OK... this is just not my day...

Booting up I get `Timeout - could not connect to s3.us-west-002.backblazeb2.com`

Here's my compose:
```
services:
  gokapi:
    image: f0rc3/gokapi:latest
    container_name: gokapi
    restart: unless-stopped
    #    environment:
    #      - GOKAPI_MAX_FILESIZE=10240000
    ports:
      - 53842:53842
    volumes:
      - data:/app/data
      - config:/app/config
volumes:
  data: null
  config: null
networks: {}
```
config.json
```
{
  "Authentication": {
    "Method": 0,
    "SaltAdmin": "abc",
    "SaltFiles": "123",
    "Username": "me",
    "Password": "abc123",
    "HeaderKey": "",
    "OauthProvider": "",
    "OAuthClientId": "",
    "OAuthClientSecret": "",
    "OauthUserScope": "",
    "OauthGroupScope": "",
    "OAuthRecheckInterval": 12,
    "HeaderUsers": null,
    "OAuthGroups": [],
    "OauthUsers": []
  },
  "Port": ":53842",
  "ServerUrl": "https://download.domain.net/",
  "RedirectUrl": "http://192.168.1.16:53842/login",
  "PublicName": "MyFileDrop",
  "DataDir": "data",
  "DatabaseUrl": "sqlite://./data/gokapi.sqlite",
  "ConfigVersion": 21,
  "LengthId": 15,
  "MaxFileSizeMB": 10240000,
  "MaxMemory": 50,
  "ChunkSize": 45,
  "MaxParallelUploads": 4,
  "Encryption": {
    "Level": 5,
    "Cipher": null,
    "Salt": "",
    "Checksum": "",
    "ChecksumSalt": ""
  },
  "UseSsl": false,
  "PicturesAlwaysLocal": false,
  "SaveIp": false,
  "IncludeFilename": false
}
```
Container is running on latest Debian
