### ISSUE TITLE
Setup with docker

### ISSUE THREAD

**Issue by Jisagi** [Forceu/Gokapi#11]
Hi, I was tryting to setup gokapi with docker-compose, but wasn't able to get everything up and running. Starting with docker-compose works fine and it creates a config file, but trying to access gokapi from a different machine does not work at all. Trying to access it with curl on the machine its running on does not work (`curl: (7) Failed to connect to 127.0.0.1 port 8084: Verbindungsaufbau abgelehnt`).
I then tried to run everything with the provided command from the readme with `docker run -it -v /home/gokapi/data:/app/data -v /home/gokapi/config:/app/config -p 8084:53842 f0rc3/gokapi:latest` with the same result. Config file is the same both ways but I cannot access the sever, neither with an apache reverse proxy nor with ip:port (or on the machine itself). I also tried to run gokapi with the default ports, but same result again.

Additionally I saw, the `LengthId` in the config is always 0, despite me setting it in the environment. The created config will never use use my value or the default 15. This happens with both docker run... and docker-compose btw.

Am I missing something?

docker-compose.yml:
```
version: "3"
services:
  gokapi:
    image: f0rc3/gokapi:latest
    container_name: gokapi
    restart: unless-stopped
    environment:
      - GOKAPI_USERNAME=Jisagi
      - GOKAPI_PASSWORD=XXXXXX
      - GOKAPI_LENGTH_ID=20
    ports:
      - "8084:53842"
    volumes:
      - /home/gokapi/data:/app/data
      - /home/gokapi/config:/app/config
```

created config:
```
{
    "Port": "127.0.0.1:53842",
    "AdminName": "Jisagi",
    "AdminPassword": "XXXXXXXXXXXXXXXXX",
    "ServerUrl": "http://127.0.0.1:53842/",
    "DefaultDownloads": 1,
    "DefaultExpiry": 14,
    "DefaultPassword": "",
    "RedirectUrl": "https://github.com/Forceu/Gokapi/",
    "Sessions": {},
    "Files": {},
    "Hotlinks": {},
    "ConfigVersion": 4,
    "SaltAdmin": "zsYecQPNEbPxhInpa62nOvWrICDyVCfoDOxotOW",
    "SaltFiles": "2z8CH4B6mkE3YoVHcXLUUg1j8lcVEuNclFe6Umq9",
    "LengthId": 0,
    "DataDir": "data"
}
```
