### ISSUE TITLE
Server is in maintenance mode, please try again in a few minutes

### ISSUE THREAD

**Issue by truthsword** [Forceu/Gokapi#203]
This was working a month ago... Now I cannot load without
`Server is in maintenance mode, please try again in a few minutes.`

```
services:
  gokapi:
    image: f0rc3/gokapi:latest
    container_name: gokapi
    restart: unless-stopped
    ports:
      - 53842:53842
    volumes:
      - data:/app/data
      - config:/app/config
volumes:
  data: null
  config: null
```

```
gokapi$ docker compose logs
gokapi  |
gokapi  | ██████   ██████   ██   ██  █████  ██████  ██ 
gokapi  | ██       ██    ██ ██  ██  ██   ██ ██   ██ ██ 
gokapi  | ██   ███ ██    ██ █████   ███████ ██████  ██ 
gokapi  | ██    ██ ██    ██ ██  ██  ██   ██ ██      ██ 
gokapi  |  ██████   ██████  ██   ██ ██   ██ ██      ██ 
gokapi  |                                              
gokapi  | Gokapi v1.9.1 starting
gokapi  | Please open http://127.0.0.1:53842/setup to setup Gokapi.
```

What am I missing?
