### ISSUE TITLE
Bug: End-to-End Encryption - Stuck at Generating

### ISSUE THREAD

**Issue by lenisko** [Forceu/Gokapi#229]
Hey there!

I wanted to test e2e encryption and got hit with missing JS file.

Looks like with this commit https://github.com/Forceu/Gokapi/commit/1951a268aa6cbb31379d7f0c8474a63e50839bc4 a `wasm_exec.min.js` was removed.

Was this planned?

PS. Thanks for tool. Out of all others, it's nearly perfect!

Latest on `docker-compose.yml`
```yml
  gokapi:
    user: 1000:1000
    container_name: gokapi
    image: docker.io/f0rc3/gokapi:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Warsaw
    volumes:
      - ./gokapi/data:/app/data
      - ./gokapi/config:/app/config
#      - ./gokapi/repo/internal/webserver/web/static:/app/static
#      - ./gokapi/repo/internal/webserver/web/templates:/app/templates
```
