### ISSUE TITLE
Host gokapi at URL with PATH

### ISSUE THREAD

**Issue by macmenco** [Forceu/Gokapi#259]
I'm trying to run gokap on a certain FQDN, hosted on a k8s cluster with traefik as ingress. The FQDN has multiple apps, each at its own path. 

So I would like to run gokapi at `https://example.com/gokapi`. But I don't seem to be able to configure the path. I'd like a feature so to configure the path at which gokapi is working. 

(I could use the traefik middleware `replacepath`, but I'm kinda limited with the middleware in the currect setup)

**Comment by Forceu** [comment]
Thanks for the feedback. I am pretty sure that gokapi only uses relative paths, but I am not 100% sure. Have you already tried it?

**Comment by macmenco** [comment]
Yes, I tried it. I'm a bit in a hurry, wil retry friday and post some logging. 

This is my gokapi config. 
```
    {
      "Authentication": {
        "HeaderKey": "",
        "HeaderUsers": null,
        "Method": 0,
        "OAuthClientId": "",
        "OAuthClientSecret": "",
        "OAuthGroups": [],
        "OAuthRecheckInterval": 12,
        "OauthGroupScope": "",
        "OauthProvider": "",
        "OauthUserScope": "",
        "OauthUsers": [],
        "Password": "blabla",
        "SaltAdmin": "blabla",
        "SaltFiles": "blabla",
        "Username": "blabla"
      },
      "ChunkSize": 25,
      "ConfigVersion": 21,
      "DataDir": "data",
      "DatabaseUrl": "sqlite://./data/gokapi.sqlite",
      "Encryption": {
        "Checksum": "",
        "ChecksumSalt": "",
        "Cipher": null,
        "Level": 0,
        "Salt": ""
      },
      "IncludeFilename": true,
      "LengthId": 15,
      "MaxFileSizeMB": 10240,
      "MaxMemory": 50,
      "MaxParallelUploads": 4,
      "PicturesAlwaysLocal": false,
      "Port": ":53842",
      "PublicName": "Prutser",
      "RedirectUrl": "https://nos.nl",
      "SaveIp": false,
      "ServerUrl": "https://mydomain.com/gokapi/",
      "UseSsl": false
    }
```

And the ingress 

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
  name: gokapi
spec:
  rules:
  - host: mydomain.com
    http:
      paths:
      - backend:
          service:
            name: gokapi
            port:
              name: http
        path: /gokapi
        pathType: Prefix
  tls:
  - secretName: gokapi-tls
status:
  loadBalancer: {}
```
