### ISSUE TITLE
Feature request: basis-auth or header based login

### ISSUE THREAD

**Issue by mindfuucker** [Forceu/Gokapi#30]
I'm running Gokapi behind [Authentik](https://goauthentik.io), so only logged-in users can access it. 

Users need to know the admin username/password if they want to upload files. Could I disable authentication or use basic-auth (user/password JS prompt) or [header based authentication](https://www.navidrome.org/docs/usage/security/#reverse-proxy-authentication) to login as admin?

**Comment by Forceu** [comment]
Thanks for your request! I added an env variable in d88a3cd to support disabled login. If you are using docker, please update to the latest dev image and set the environment variable `GOKAPI_DISABLE_LOGIN`  to `true`on the first start. You can then add an authentication for the `/admin` url. Let me know if that works for you!

**Comment by mindfuucker** [comment]
Hi Marc,
I don't have any experience in running applications without Docker.  Four days ago the latest dev image was not yet available.  I downloaded go and build the project, then exported the environment variable and ran ./gokapi:
![image](https://user-images.githubusercontent.com/5075692/144762706-fcfdfac9-3550-4629-b231-f4777a9b0a7e.png)

When browsing to /admin it still shows me the Gokapi login prompt. I will try again with the docker dev-image.

**Comment by mindfuucker** [comment]
The docker-dev image worked flawlessly. I was able to get it up and running in a couple of minutes. This was my Docker Compose file for posterity's sake:
```
services:
   Gokapi:
      image: f0rc3/gokapi:latest-dev
      restart: unless-stopped   
      environment:
         - GOKAPI_USERNAME=<username>
         - GOKAPI_PASSWORD=<password>
         - GOKAPI_DISABLE_LOGIN=true
      ports:
         - "53842:53842"
      volumes:
         - /nfs/Shared:/app/data
         - ./config:/app/config
```

Restricting access in Authentik to certain pages is difficult to do. The inverted is actually easier to do. Authentik supports regex filters that by-pass authentication. This is what I came up with:
![image](https://user-images.githubusercontent.com/5075692/144812193-c018f799-ba7d-4205-b030-50d857e173c1.png)
