### ISSUE TITLE
Template customization in Docker panics

### ISSUE THREAD

**Issue by fritzfranzke** [Forceu/Gokapi#41]
# Synopsis

When running Gokapi `v1.3.1` using Docker template customization according to the [documentation](https://gokapi.readthedocs.io/en/latest/advanced.html#customising) is broken. Browsing the login page works fine (and changes are visible), but when attempting login an error is thrown.

# How to reproduce
1. Clone project
2. `cp -r Gokapi/internal/webserver/web/templates .`
3. Change a template file, for example `templates/data/templates/string_constants.tmpl`
4. Launch the following `docker-compose.yml`:

```
version: '3.7'
services:
  gokapi:
    image: f0rc3/gokapi:latest
    container_name: gokapi
    ports:
      - 53842:53842
    environment:
      - GOKAPI_USERNAME=admin
      - GOKAPI_PASSWORD=admin
    volumes:
      - ./data:/app/data
      - ./config:/app/config
      - ./templates:/app/templates
```

# Stacktrace
```
gokapi  | 2022/01/24 10:48:39 http: panic serving x.x.x.x:XXXX: template: html_header.tmpl:48:18: executing "header" at <.IsLogoutAvailable>: can't evaluate field IsLogoutAvailable in type *webserver.UploadView
gokapi  | goroutine 41 [running]:
gokapi  | net/http.(*conn).serve.func1(0xc000308500)
gokapi  |       /usr/local/go/src/net/http/server.go:1824 +0x153
gokapi  | panic(0xb2f080, 0xc00032a180)
gokapi  |       /usr/local/go/src/runtime/panic.go:971 +0x499
gokapi  | Gokapi/internal/helper.Check(...)
gokapi  |       /compile/internal/helper/OS.go:61
gokapi  | Gokapi/internal/webserver.showAdminMenu(0x17bf070, 0xc000348380, 0xc000336600)
gokapi  |       /compile/internal/webserver/Webserver.go:335 +0x14a
gokapi  | net/http.HandlerFunc.ServeHTTP(0x1689a18, 0x17bf070, 0xc000348380, 0xc000336600)
gokapi  |       /usr/local/go/src/net/http/server.go:2069 +0x44
gokapi  | net/http.(*ServeMux).ServeHTTP(0x1b3f6e0, 0x17bf070, 0xc000348380, 0xc000336600)
gokapi  |       /usr/local/go/src/net/http/server.go:2448 +0x1ad
gokapi  | net/http.serverHandler.ServeHTTP(0xc0002a2000, 0x17bf070, 0xc000348380, 0xc000336600)
gokapi  |       /usr/local/go/src/net/http/server.go:2887 +0xa3
gokapi  | net/http.(*conn).serve(0xc000308500, 0x17c1dc0, 0xc000320480)
gokapi  |       /usr/local/go/src/net/http/server.go:1952 +0x8cd
gokapi  | created by net/http.(*Server).Serve
gokapi  |       /usr/local/go/src/net/http/server.go:3013 +0x39b
```
