### ISSUE TITLE
File not available after upload

### ISSUE THREAD

**Issue by Chris1320** [Forceu/Gokapi#91]
Whenever I try to upload a file, there is a chance that it will show an error when I open the file's URL.

![image](https://user-images.githubusercontent.com/74256376/222911170-6b7b2acc-0201-4ead-96b6-1f550b852887.png)

I used the following settings to upload the file:

- Limit Downloads: 10 Downloads
- Expiry: 1 Day
- Password: test1243

When I open the `data/` folder in Docker, this is the output:

![image](https://user-images.githubusercontent.com/74256376/222911502-fab1df24-f3f0-4409-afcb-286a2daeaa4d.png)

I also noticed that when the upload finishes and I refresh my browser, the uploaded file is lost in the uploaded files list, but still present in the server's filesystem.

-----

Docker Configuration:

- Encryption: Level 0
- Storage: Local
- Authentication: Username/Password

**Comment by Forceu** [comment]
Thanks for the report. Unfortunately I am unable to reproduce the problem. Can you please post the command you are using to setup the docker container? Also, if you upload a file and have the webbrowsers' console open during the upload (normally by pressing F12), are any error messages displayed? Also, on what filesystem are you storing the data volume?

**Comment by Chris1320** [comment]
Strange, I just started the container again today without changing anything in the `docker-compose.yaml` file, and I think it's now working fine.

I tried uploading several files using the same settings I described above (~28 KB to ~40 MB in file size) and everything is now accessible. The console returns an `OK` result.

I'll update with proper logs next time if it happens again. Thank you.

-----

**filesystem**: NTFS (running on Docker Desktop for Windows)
**`docker-compose.yaml` file**:

```yaml
# Project homepage: https://github.com/Forceu/Gokapi

version: "3"

services:
    gokapi:
        container_name: gokapi
        image: "f0rc3/gokapi:latest"
        restart: unless-stopped
        volumes:
            - ./data/data:/app/data
            - ./data/config:/app/config
        ports:
            - 8099:53842
        environment:
            - USER_UID=1000
            - USER_GID=1000
```
